services:
  - type: web
    name: acme-salary-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: acme-salary-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://acme-salary-backend-fzk5.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
